# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-22 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_id',
            field=models.CharField(default='MTLXXX', max_length=200),
        ),
        migrations.AlterField(
            model_name='creview',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
    ]
