# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-22 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200322_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creview',
            name='pub_date',
        ),
    ]
