# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-30 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='creview',
            name='is_ano',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preview',
            name='is_ano',
            field=models.BooleanField(default=False),
        ),
    ]
